drop:
  base: # Default drop rates
    NETHER_WART_BLOCK: 40
    WARPED_WART_BLOCK: 40
    SHROOMLIGHT: 60
  player:
    NETHER_WART_BLOCK: 70
    WARPED_WART_BLOCK: 70
    SHROOMLIGHT: 90

  # The hoe is the most efficient tool for breaking organic blocks since 1.16.
  always-drop-when-hoe-used: true
  # TNT explosions have a 100% drop rate since 1.14. At true, a block destroyed by a TNT will use the players' rates.
  tnt-use-players-rate: true

# Defines the distance to be evaluated from the stem for decaying leaves.
max-distance-from-stem: 4
